import type { Metadata } from "next";
import "./globals.css";

// import { Roboto } from 'next/font/google'

// const roboto = Roboto({ subsets: ['vietnamese'], weight: ['100', '300'] })
import localFont from 'next/font/local'
 
// Font files can be colocated inside of `pages`
const myFont = localFont({
  src: [
    {
      path: './Roboto-Thin.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './Roboto-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ]
})
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={myFont.className}
      >
        <header>kkkaak</header>
        {children}
      </body>
    </html>
  );
}
