import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from 'next/font/google'
import Header from "@/components/ui/header"
import { Toaster } from "@/components/ui/toaster"
import AppProvider from "./AppProvider"
import { cookies } from "next/headers"
const inter = Inter({ subsets: ['vietnamese'] })

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <Toaster />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AppProvider initialSessionToken={cookies().get('sessionToken')?.value}>
              <Header />
              {children}
            </AppProvider>
          </ThemeProvider>
      </body>
    </html>
  );
}
